### ISSUE TITLE
Geocoding doesn't happen on device create or update

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#106]
https://github.com/fablabbcn/smartcitizen-api/blob/4b38f7cbc5ae71768ca17eb3782ca9b406018e80/app/models/device.rb#L39

Every time a device is created geocoding should use the `latitude` and `longitude` properties to fill the location attribute on the device model. 

The location attribute looks like: `{"city": "Barcelona", "state": "Catalunya", "address": "Carrer de Sancho de Ávila, 154, 08018 Barcelona, Barcelona, Spain", "country": "Spain", "state_code": "CT", "postal_code": "08018", "country_code": "ES"}`

Once the issue is fixed we should run the task to geolocate all the devices with missing location
 
https://github.com/fablabbcn/smartcitizen-api/blob/4b38f7cbc5ae71768ca17eb3782ca9b406018e80/app/models/device.rb#L210

**Comment by pral2a** [comment]
Great! Go for it when you have some time. 

What Google Account should we use?

**Comment by pral2a** [comment]
Is there anything missing from my side here?

**Comment by viktorsmari** [comment]
More services like Geolocation, Elevation, Places API etc, have now been added to this particular API key.
