### ISSUE TITLE
Add taxonomies for sensors

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#114]
Add support for "tags" on the sensor model. We want to assign tags from a list to a sensor. Multiple tags per sensor will be supported.

That's the actual sensor model JSON output with the new tags:

```
{
    "id": 14,
    "uuid": "ac4234cf-d2b7-4cfa-8765-9f4477e2de5f",
    "parent_id": null,
    "name": "BH1730FVC",
    "description": "Digital Ambient Light Sensor",
    "unit": "Lux",
    "created_at": "2015-02-02T18:24:56Z",
    "updated_at": "2015-07-05T19:57:36Z",
    "tags": ["environmental", "light", "digital"],
    "measurement": {
        "id": 3,
        "uuid": "50aa0431-86ac-4340-bf51-ad498ee35a3b",
        "name": "light",
        "description": "Lux is a measure of how much light is spread over a given area. A full moon clear night is around 1 lux, inside an office building you usually have 400 lux and a bright day can be more than 20000 lux."
    }
}
```

We can replicate the same structure as with device tags:

https://github.com/fablabbcn/smartcitizen-api/blob/dc3117adc9d20b47706b20e04f55e15e2c408db9/app/models/device.rb#L91

That means we will need to create a `tags_sensors` (as we have `tags` for devices, we might need to find a better name) for the tags list and then  a `sensors_tags` (as we have `devices_tags` for devices) to keep the binding

**Comment by viktorsmari** [comment]
Working on it at #118

**Comment by pral2a** [comment]
👍
