### ISSUE TITLE
Create device extremely slow

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#121]
All operations involving the creation of a new device are far slower (from 10-20sec) than before

`POST /v0/devices`  

https://github.com/fablabbcn/smartcitizen-api/blob/c3c1fa1b55c6355346af343df314315825d5776d/app/controllers/v0/devices_controller.rb#L53

`POST v0/onboarding/register`

https://github.com/fablabbcn/smartcitizen-api/blob/c3c1fa1b55c6355346af343df314315825d5776d/app/controllers/v0/onboarding/device_registrations_controller.rb#L19

Maybe this is due to the change from G Maps to Open Street Maps API for reverse geolocation https://github.com/fablabbcn/smartcitizen-api/commit/dc3117adc9d20b47706b20e04f55e15e2c408db9

**Comment by pral2a** [comment]
![screenshot 2018-11-08 17 41 49](https://user-images.githubusercontent.com/74249/48270954-84fa4e00-e43b-11e8-973e-c340ba1f8245.png)

**Comment by viktorsmari** [comment]
https://sentry.fab.city/sentry/apismartcitizenme/issues/42/?query=is:unresolved

**Comment by viktorsmari** [comment]
Fixed via 1228c0364499b48a7174599a3fef89015a806c2d

**Comment by pral2a** [comment]
👍
