### ISSUE TITLE
Idea: add monthly email digests

### ISSUE THREAD

**Issue by viktorsmari** [fablabbcn/smartcitizen-api#142]
Users can opt in to get **Monthly digests** emails containing useful metrics.

* The warmest day was Tuesday 22.feb
* The most polluted day was..
* The best / worst air quality was
* Your device 1234 collected 52.567 data points

**Comment by oscgonfer** [comment]
We can add this as features actually on the front-end, instead on an email. This would be easy to implement, and also engage more on the front-end usage.
