### ISSUE TITLE
Request: Ransack search for online devices

### ISSUE THREAD

**Issue by henrikkorsgaard** [fablabbcn/smartcitizen-api#169]
Hi folks,

I would really love some more options in the Ransack search parameters, e.g. being able to search for online devices (system_tags?) and perhaps human-readable locations, e.g. city, country etc. AFAIK this is not currently possible with the permitted parameters:

https://github.com/fablabbcn/smartcitizen-api/blob/e15316920ef06ca4ab14f585004e3480f8c03b76/app/controllers/v0/devices_controller.rb#L130-L143

Best,
Henrik

**Comment by pral2a** [comment]
Hi!

We'll look at it with @viktorsmari 

At the moment remember you can combine multiple queries. 

i.e. if you only want SCK 2.1 sensors active today in the area of Barcelona

https://api.smartcitizen.me/v0/devices?q[kit_id_eq]=26&q[last_reading_at_gt]=2019-05-07T00:00:00Z&near=41.401108,2.215319

**Comment by viktorsmari** [comment]
Did you check the https://developer.smartcitizen.me/#basic-searching and https://github.com/activerecord-hackery/ransack/wiki/Basic-Searching

An `online` `system_tag` is when the `last_recorded_at` is > 60 minutes.
So using the `[last_recorded_at_gt]=` The time now - 60 minutes (or whatever you like)

**Comment by henrikkorsgaard** [comment]
Thank you. I am familiar with both your API and the Ransack syntax/query structure. I was just wondering if, since it is in your data model, that it would be possible to query directly for online devices. 

I use it for teaching and thought it would make sense to have a more direct mapping between the device data model and the available queries.
