### ISSUE TITLE
Add a "postprocessing_info" property on device

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#179]
Enhance the device model with a `postprocessing_info` with a JSON type as the existing `hardware_info` property

The following property should be updatable with a `PATCH v0/devices/1322/` on `device.postprocessing_info`

The property will be used by the Sensors Analysis Framework to store particular data on the postprocessing requirements and status of each sensor

**Comment by oscgonfer** [comment]
Thank you @viktorsmari and @pral2a
