### ISSUE TITLE
Add filtering possibility for postprocessing_info and hardware_info in ransack

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#187]
Hi,

For data analysis purposes, we would need to implement some filtering of `null` vs. `not_null` as described here for other properties: https://developer.smartcitizen.me/#basic-searching

The idea is only to be able to differentiate when `postprocessing_info` is `null` or not, and the same in `hardware_info`: https://api.smartcitizen.me/v0/devices?q[postprocessing_info_not_null] or similar.

**Comment by pral2a** [comment]
@viktorsmari I assign you that issue to see if you can have it a look

The new stations are [shipping](https://twitter.com/derive_LAB/status/1337492449581801477) and @oscgonfer is working to implement the end-to-end post processing flow

**Comment by viktorsmari** [comment]
@oscgonfer did you try some of the Search matchers available here: https://github.com/activerecord-hackery/ransack#search-matchers ?

Mainly these:

```
*_null | is null |  
*_not_null | is not null
```

I have not tried it yet, but let me know if you have. If it does not work we might need to do something custom. Remember that the column is a `jsonb` - maybe we need something custom for that

**Comment by viktorsmari** [comment]
The solution is like this:

`https://api.smartcitizen.me/v0/devices?q[postprocessing_info_not_null]=1`

We need to add the `=1` at the end

https://github.com/activerecord-hackery/ransack/wiki/Basic-Searching#true
> The '1' indicates that to Ransack that you indeed want to check the truthiness of this field. The other truthy values are 'true', 'TRUE', 't' or 'T'

**Comment by oscgonfer** [comment]
That looks great. Tested and works fine.

Thanks @viktorsmari

**Comment by pral2a** [comment]
@viktorsmari whenever you have time I think it will be good to bring some of this to our API docs. Filter options for devices is a recurrent question people asks about our API on hackatahon, etc

**Comment by viktorsmari** [comment]
Yes, I have noticed that, any ideas how we can improve it?

The docs already say it's possible (with examples) linking to Ransack docs (John Reese wrote this in the docs in 2015):

```
Basic Searching
Similar to the pagination, you can filter and sort most responses that return more than one result. 
This is done with the ransack library.

https://github.com/activerecord-hackery/ransack/wiki/Basic-Searching
```

Screenshot:
![2020-12-15_11-14-16](https://user-images.githubusercontent.com/1689020/102201652-b2414200-3ec6-11eb-83c6-52d48cc4a26b.png)

Maybe we need to mention Ransack and link to it in more places in the docs?

**Comment by viktorsmari** [comment]
I added the later `info` box, maybe that helps. It links to our Basic Searching section

![2020-12-15_11-22-10](https://user-images.githubusercontent.com/1689020/102202592-cdf91800-3ec7-11eb-910e-2fb43ed570af.png)

**Comment by oscgonfer** [comment]
Examples on how to filter the `postprocessing_info` as you did above would be helpful too I think.

Maybe in the info box you could also refer to the null/not_null section?
