### ISSUE TITLE
Add new property to the orphan_device model

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#193]
We are considering the possibility the onboarding web-app at [start.smartcitizen.me](https://start.smartcitizen.me/) can populate [postprocessing](https://github.com/fablabbcn/smartcitizen-api/blob/7ac0f044ce59137f2317db3dfdfcf3e503f37d2f/app/models/device.rb#L26), the same we already populate other properties such as `kit_id`, `name`, etc:

https://github.com/fablabbcn/smartcitizen-api/blob/7ac0f044ce59137f2317db3dfdfcf3e503f37d2f/app/models/orphan_device.rb#L16-L23

And then create a new device using them

https://github.com/fablabbcn/smartcitizen-api/blob/7ac0f044ce59137f2317db3dfdfcf3e503f37d2f/app/controllers/v0/onboarding/device_registrations_controller.rb#L18-L28

**Comment by oscgonfer** [comment]
For now, this will need to be reconsidered as there might be changes in the overall architecture of the onboarding, and the platform models. For SCK2.1, it will be still valid, but the migration should consider merging that use case into a simpler approach in the long-term.
