### ISSUE TITLE
"data" is missing in the "devices/world_map"

### ISSUE THREAD

**Issue by antoine3000** [fablabbcn/smartcitizen-api#197]
Hi,

The API [documentation](https://developer.smartcitizen.me/#world-map-of-devices) says that the set "devices/world_map" contains the "data" information, but this is [not](https://api.smartcitizen.me/v0/devices/world_map) the case. Would it be possible to add it?

Thank you!

**Comment by pral2a** [comment]
Sorry @antoine3000 we will update the documentation accordingly. We actually reduced the `devices/world_map`  end-point to reduce load times in front and backend as it already contains a lot of data. 

For getting all `devices` data I will suggest querying `device` and use pagination. Also, `devices` allows you to filter devices in backend to reduce the overall data you request and filter in front-end https://developer.smartcitizen.me/#basic-searching

**Comment by antoine3000** [comment]
Thanks @pral2a for your quick answer! I'll rethink my strategy.

**Comment by pral2a** [comment]
What specific properties are you actually looking for?

**Comment by antoine3000** [comment]
I would like to display a visual index on a single page that shows all kits - or a selection - with the latest reading of a sensor type. For example, display all kits with the latest particulate matter reading - for each.

**Comment by antoine3000** [comment]
@pral2a I found a (_quick_ and _dirty_) way to do it

**Comment by pral2a** [comment]
In case it helps. In the current implementation of http://now.smartcitizen.me/ I retrieve all devices with ` devices/world_map` and then I populate `data` only when I receive data from a device via WebSockets. That means devices that published while you are looking at the page you get to see data, in this case, battery level but could be anything, while devices that don't publish remain only with the information provided by ` devices/world_map`.

Another option as I mentioned in the previous comment will be to use `device` and filter in advance in backend, you can filter by kit_id (i.e. sck 2.0, 2.1, etc), you can filter by location, etc. You don't need to implement it now but it means the solution will be more scalable as the browser won't need to deal with the full list of devices. For example can use the `kits` end-point to obtain all the `kit.id` that contains an specific `sensor`  and then can filter those devices like. i.e. https://api.smartcitizen.me/v0/devices?q[kit_id_eq]=21

**Comment by antoine3000** [comment]
Thank you very much for your answer @pral2a.

I now realise that WebSockets is not very usable in my scenario: I would like to view the real time data on a reduced portion of the kits. But since there is only one topic, I have to wait for a full loop before updating the data of a specific kit. This makes the process very slow.

Indeed developing a small backend could relieve the browser but it will complicate this little project.

Let me meditate on that :-)

**Comment by pral2a** [comment]
Just to clarify, what we do in other dashboards or sites is to retrieve the devices names and minimal metadata using `devices/worldmap`, then filter the devices in front-end and after populating the missing data such as latest sensor data, etc, using:

-  `device/{device_id}` on user action or with a timeout, long-polling style. That's the way the main front-end refreshes the data every 15s i.e. https://smartcitizen.me/kits/9721 That works well when you only poll one or a few devices as the API throttle will block you if you do too many requests per minute.

- Websockets (WS) every time device publishes. With it you'll get a push whatever the device publishes, even if there's only a single topic, you'll get them all one after another. That's what http://now.smartcitizen.me/ does.  However, the bottleneck might happen if the number of devices grows as your front-end might need to process a lot of messages per minutes (currently is about 6 devices per second).  Also, the WS API might change in the future. That means if you succeed to accomplish your work without WS its event better.
