### ISSUE TITLE
Consolidate user assets implementation

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#223]
Review #127 

Verify implications of images.smartcitizen.me being deprecated on patforms user profiles

https://images.smartcitizen.me/s100/avatars/b4b/1djs79t.earth.jpg
https://smartcitizen.me/users/6556

**Comment by timcowlishaw** [comment]
Closing as a dupe of #166 - This should be partially dealt with in #271 with the remaining work to be done after i've updated smartcitizen-web to always use the new image.
