### ISSUE TITLE
SC data forwarding to other projects

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#226]
As part of new projects currently running (3 out of 3 ask for this in one way or another), we need to look at how data is made available in other platforms, without necessarily going through the API all the time. 

Solutions that have been discussed:

- **Forward data (push)** to another MQTT-broker or the current one, on another topic (s), and have other platforms connect to it based on a json we define. Then they ingest data in their platform, this is probably the easiest for us, not so much for others
- Expose data directly via **more standard APIs on top of our database** (not an easy task - actually we could die trying) such as STA, STAplus. A limited integration could happen, but plenty of issues can emerge from this, such as _expand_ type of requests to endpoints that can request the whole database (STA allows for that)
- **Forward data to FROST Server instance**, maybe the _least bad_ option. This means replicating databases, and risk of losing sync at some point. However, it makes a standalone standard instance that we can upgrade as the standard progresses. For instance, STAplus changes, or security improvements (confidentiality) are on their end. However, these standards are not so easy to implement and there are hidden caveats, for instance, a large overhead per observation. This means we end up maybe having to implement another way timeseries are handled in STA

**Comment by oscgonfer** [comment]
This was agreed upon after discussion internally. See: https://github.com/fablabbcn/smartcitizen-api/issues/307

**Comment by oscgonfer** [comment]
Actions in `storer.rb` and `raw_storer.rb` changes in https://github.com/fablabbcn/smartcitizen-api/blob/ad27c71fa5e194555bc5e1d5a30fd815f4a58e3c/app/models/raw_storer.rb#L73 and in https://github.com/fablabbcn/smartcitizen-api/blob/ad27c71fa5e194555bc5e1d5a30fd815f4a58e3c/app/models/storer.rb#L47 to:

- [ ]  `data-received` queue is removed and replaced by a `mqtt_publisher` that handles the forwarding (see details below)
- [ ] `ws` service to be removed after confirmation that it's not in `web` or `onboarding`

The forwarding *of those devices that are allowed* (see #307) should contain the same `payload` as in https://github.com/fablabbcn/smartcitizen-api/blob/ad27c71fa5e194555bc5e1d5a30fd815f4a58e3c/app/models/raw_storer.rb#L73 (TBC) and have a different `topic` such as:

`forward/devices/<client-id>/<device-id>/readings`

For now, <client-id> is a unique `hash` tied to a `user` but in the future could be tied to `communities` or `experiments`. This allows to filter the connections to the broker and who gets what.

**Comment by oscgonfer** [comment]
Let's use a combination of both:
- MQTT topic would be: 'forward/<secret>/device/<device-id>/...' with a secret `username` (both would be long hex strings)
- The auth would be on a http request on api.smartcitizen.me/v0/forward (TBC), using the control flow from emqx as detailed here: https://www.emqx.io/docs/en/latest/access-control/authz/http.html
- We `ignore` in case of not matching, so that we can then check based on the `ACL` file that would handle the rest

**Comment by timcowlishaw** [comment]
Hey folks, i think this is ready for a test on thursday, with the changes @oscgonfer describes above!

**Comment by oscgonfer** [comment]
Moved to https://github.com/fablabbcn/smartcitizen-api/issues/307
