### ISSUE TITLE
API endpoints for measurements, sensors

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#229]
Add endpoints for the creation or modification of the parts of the data model:

- ~Kits~
- Measurements
- Sensors

This would allow an easier creation of new items in those tables. The implementation for adding the `components` (not listed above) to the kit needs to also be reviewed.

**Comment by oscgonfer** [comment]
https://github.com/fablabbcn/smartcitizen-api/issues/181

**Comment by timcowlishaw** [comment]
I *think* this is already done, but perhaps not documented - @oscgonfer to confirm!
