### ISSUE TITLE
Kairos docker image no longer builds due to disappeared base image

### ISSUE THREAD

**Issue by timcowlishaw** [fablabbcn/smartcitizen-api#233]
Our docker image for Kairos is based on `java:8-alpine` which was deprecated a few years back, as a conseqence it's no longer possible to build the kairos container. This isn't an immediate problem (there's a workaround for local development by using the staging kairos deployment to develop against) but capturing here as it'll impact future maintenance and migration

**Comment by oscgonfer** [comment]
Worked on in: https://github.com/fablabbcn/smartcitizen-api/pull/247
