### ISSUE TITLE
Two users with same email?

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#294]
So I have been reported an issue in which the log-in of a user gets redirected to another one on the onboarding. The steps of the onboarding are:

1. Input email
2. Ask for password (with the corresponding username)
3. ...

So in Step 2, a weird case happened, in which two users shared the same email, which obviously shouldn't happen. This hasn't happened with our `admin` intervention, so there should is some bug that allowed two users to share email...

**Comment by oscgonfer** [comment]
So one of the potential rootcauses for this is that we have no check on the web/profile/edit.

**Comment by pral2a** [comment]
In principle the standard user creation method should validate that on backend.

Also the onboarding app that should check that in a combination of front-end / backend. However, it might be something fails there? 🍝

**Comment by oscgonfer** [comment]
Since this issue is widespread: 

1. We will unify all accounts that have the same email onto a single one. All devices will be moved over to that account
2. Users can use password recovery if they can't access it (we will announce it on the forum)
3. Users with no email will be deleted, including those that have devices. However, the devices owned by those users with no email, will be moved to user: 6556 until reclaimed

Then, we won't allow for create or update operations where email == `null` or `not-unique`.

**Comment by timcowlishaw** [comment]
Done in 51a3a984fda! we'll need to run the two rake tasks after deploying to production.

**Comment by timcowlishaw** [comment]
Procedure for running this in live:
Bring down everything apart from the db container temporarily
```
docker exec -t smartcitizen-api-db-1 pg_dumpall -c -U postgres > dump_pre_user_deduplication.sql
docker compose run --no-deps app bundle exec bin/rake users:remove_null_emails | tee remove_null_emails.log
docker compose run --no-deps app bundle exec bin/rake users:deduplicate_emails | tee deduplicate_emails.log
docker exec -t smartcitizen-api-db-1 pg_dumpall -c -U postgres > dump_post_user_deduplication.sql
```
After each rake task, verify that the provided counts match up!

**Comment by timcowlishaw** [comment]
Opening this until we run the tasks on production
