### ISSUE TITLE
Extra fields to measurements and sensors

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#295]
So, as part of our efforts to be a bit more [_FAIR_](https://en.wikipedia.org/wiki/FAIR_data) and given that we are currently forwarding data to other _Standard_ platforms (see https://citiobs.demo.secure-dimensions.de/staplus/v1.1), I suggest an enhancement to our `Measurements` and `Sensors` model to contain additional information, that would make our platform more traceable and _more_ "interoperable".

### Measurements

Add `definition` field, with type `str`, to contain a link to a standard vocabulary definition for the measured property, such as: https://vocabs.lter-europe.net/envthes/en/page/?uri=http://vocabs.lter-europe.net/EnvThes/21579

### Sensors

Add three fields: `datasheet`, `encoding` and `unit_definition`:
- `datasheet` (`str`): will contain a link to a datasheet, either on docs.smartcitizen.me or storage.smartcitizen.me containing the sensor datasheet
~- `encoding` (`str`) - (_this one I am not totally sold on_) will contain the encoding type, such as: `application/pdf`~
- `unit_definition` (`str`) - would include a link to another vocabulary with units definition such as: https://qudt.org/vocab/unit/PERCENT

~These properties should be subject to CRUD operations by `admin` role only once we work on: https://github.com/fablabbcn/smartcitizen-api/issues/229~

**Comment by timcowlishaw** [comment]
Addressed in #332
