### ISSUE TITLE
Better name for `hardware.info`?

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#309]
Easy one, do we think that we can find a better, more understandable name, for `hardware.info`? We were talking with @pral2a about it and we thought that it would be weird for an user to see it, and it be `[filtered]`. Maybe something like `last_report`?

**Comment by timcowlishaw** [comment]
Hmm very happy to do this, but not sure `last_report` is particularly  descriptive either (i'd expect that to be the datetime of the last time the device updated the info). Maybe `last_reported_hardware_info`?

**Comment by oscgonfer** [comment]
what about `hardware.last_status` or `hardware.last_status_report`

**Comment by timcowlishaw** [comment]
ok perfect, last_status_message it is!

**Comment by timcowlishaw** [comment]
Done in 5b1e73f!
