### ISSUE TITLE
It's OK to steal `legacy` devices

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#310]
As the title says, it's OK to steal `legacy` devices by typing the `MAC` address on a newly created one. The idea is that, if you are in possession of the hardware, you should be able to register a new device.

**Comment by oscgonfer** [comment]
This, @timcowlishaw should revert what we did last week, leaving only the error on  server side regarding the MAC address validity (regex check)

**Comment by timcowlishaw** [comment]
Fixed in 5ce04c6 on the refactor branch!
