### ISSUE TITLE
Don't know how to set a country for a `user`  or `me`self

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#311]
I am trying to set a `country` for a `user` via `PUT` but I am not able to figure it out. It seems like we do not allow to update the `country`?

This is for `me`:

https://github.com/fablabbcn/smartcitizen-api/blob/c93097e5072c90d2c8df65c522aab82312b6e583/app/controllers/v0/me_controller.rb#L33

In the front-end, there is a convertion table between `country_codes` and `country`, so I assume there's something I am missing in the rationale behind this?

**Comment by timcowlishaw** [comment]
Fixed in e736331!
