### ISSUE TITLE
Can't unset `user` country

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#313]
I am trying to test https://github.com/fablabbcn/smartcitizen-api/issues/311 fix. However, I am now not able to unset it.
However, if I send an empty `country`, I am still seeing the same country as the last one I set.

See here (I unset the town and the country):

https://staging-api.smartcitizen.me/v0/users/4059

**Comment by timcowlishaw** [comment]
aha you have to set an empty country_code (explicitly `null`, not just missing the key), eg `PATCH /users/:id` with `{
    "country_code":  null, "access_token": "SECRET" }`

**Comment by oscgonfer** [comment]
Aha! Front-end issue then... solved!
