### ISSUE TITLE
Improve auth mechanisms for MQTT broker subscription

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#322]
Currently, our MQTT publishing/subscription auth logic is:
- allow all to publish
- deny all to subscribe EXCEPT certain users/IPs

We can improve the user auth part to be more secure by building upon the work done in https://github.com/fablabbcn/smartcitizen-api/pull/318, by also having checks for the type of user in the platform and by passing the auth bearer.

**Comment by timcowlishaw** [comment]
Implemented in https://github.com/fablabbcn/smartcitizen-api/pull/318
