### ISSUE TITLE
`sidekiq` retries seems to be creating multiple components on a `device`??

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#327]
Hi,

A critical issue that has started happening after our sidekiq retry test (I believe) is that it seems that we are violating uniqueness of components/sensors in the creation of a device:

https://api.smartcitizen.me/v0/devices/17537

You can see it here:

https://smartcitizen.me/kits/17537

![image](https://github.com/fablabbcn/smartcitizen-api/assets/13301321/8a88d248-4578-40e6-8cb0-154777a4c41c)

Weird thing is... some sensors are there 3 times, others 2 times...

**Comment by timcowlishaw** [comment]
Oh that's extremely strange, I will take a look asap!

**Comment by timcowlishaw** [comment]
Fixed in #328 !
