### ISSUE TITLE
Review priviledges and roles, is_private should be allowed for anyone

### ISSUE THREAD

**Issue by oscgonfer** [fablabbcn/smartcitizen-api#349]
Admin: everything

Researchers:
- Rate limit whitelisted
- Enable forwarding (for now kept here)
- is_private -->  open by default, but should be allowed for everyone

@timcowlishaw can you review and update the list?

**Comment by timcowlishaw** [comment]
See: https://docs.google.com/spreadsheets/d/19X8qGoCUn2cXaL547OjBEan-NtgYFeaPV44aO9MAwjA/edit?gid=0#gid=0 - i'll amend the "is private" flag so it's open to everyone today!

**Comment by timcowlishaw** [comment]
- Fresh world map should reflect device privacy for currently logged in user
- the cached "world map" endpoint should ONLY show public devices
- Only admins can set the is_test flag.
