### ISSUE TITLE
Apply new front-end styles to email notifications

### ISSUE THREAD

**Issue by pral2a** [fablabbcn/smartcitizen-api#89]
## Example of the 3 possible emails with the existing designs

![screen shot 2018-07-02 at 11 55 04](https://user-images.githubusercontent.com/74249/42157801-04542774-7def-11e8-83d7-4235b1ec5475.png)
![screen shot 2018-07-02 at 11 55 18](https://user-images.githubusercontent.com/74249/42157802-046cf47a-7def-11e8-9bf8-92ddce218071.png)
![screen shot 2018-07-02 at 11 55 23](https://user-images.githubusercontent.com/74249/42157803-0487a216-7def-11e8-8e07-4a973334c16d.png)

## Source files

https://github.com/fablabbcn/smartcitizen-api/tree/master/app/views/user_mailer

Ask @marcelirodriguez for the design blueprints / style guide

**Comment by pral2a** [comment]
@viktorsmari Note also there's a minor bug here:

https://github.com/fablabbcn/smartcitizen-api/blob/master/app/views/user_mailer/device_archive.html.erb#L33

![42157802-046cf47a-7def-11e8-9bf8-92ddce218071](https://user-images.githubusercontent.com/74249/42158270-42722bae-7df0-11e8-8fa0-b49eb1bafee0.png)

**Comment by viktorsmari** [comment]
@marcelirodriguez How should we style the emails?

**Comment by viktorsmari** [comment]
Emails now look like this:
![2019-02-11_07-47-37](https://user-images.githubusercontent.com/1689020/52549035-66587a00-2dd1-11e9-9108-34ea441d8fb3.png)

- [ ] Font `kanit` is missing

@marcelirodriguez any more comments?

**Comment by pral2a** [comment]
The notifications management button is too big compared to the stopped publishing text. You don’t even know what the email it’s about unless you read it carefully. I suggest also to add a link to the device URL.

**Comment by viktorsmari** [comment]
@pral2a a link to the device on the Angular app or on the API?

**Comment by viktorsmari** [comment]
I added a link to the Angular App and made the button smaller.
![2019-02-11_10-29-32](https://user-images.githubusercontent.com/1689020/52554717-f86b7d00-2de7-11e9-88da-5a84b6536ed3.png)

There is a problem with the Button if the user is NOT already logged in to the Angular app, he will be redirected to the frontpage. The Angular app does not even ask him to log in or remembers the old path.
This means the button is kind of useless at the moment.
